### ISSUE TITLE
ArrayStrategy Remove

### ISSUE THREAD

**Issue by svanderbeck11** [adamhooper/js-sorted-set#10]
ArrayStrategy.remove seems like it would be better off checking the comparator == 0 vs this.data[index] !== value. Can lead to problems otherwise with seemingly identical objects not evaluating to equal.

**Comment by adamhooper** [comment]
I think red-black tree strategy has the same behavior.

@svanderbeck11 Could you please describe a use case you'd like this library to support that it doesn't support right now?

**Comment by svanderbeck11** [comment]
Hi Adam,
Just doing some quick experimenting to check the library for a project we have where sorted sets will help a ton with performance. Basically just doing an action like:

`let mySet = new SortedSet(
     comparator:myUserComparator,
     strategy: SortedSet.ArrayStrategy,
     onInsertConflict: SortedSet.OnInsertConflictReplace);

mySet.insert({userID:1,first:"John",last:"Smith"}); 
mySet.insert({userID:2,first:"Jane",last:"Doe"}); 

mySet.remove({userID:1,first:"John",last:"Smith"}); //throws an error and not found. Ideally would be found
mySet.contains({userID:1,first:"John",last:"Smith"}); //evaluates to false. Ideally true based on comparator`

**Comment by adamhooper** [comment]
I looked at the code, and it looks like this change won't impact speed much at all. It seems more intuitive than comparing object identities, too.

So now, js-sorted-set supports this in all strategies.

**Comment by svanderbeck11** [comment]
One other thing I was thinking was something like an Initialize method.  So when we first construct the set we can pass in an initial set of data. At least on the ArrayStrategy, I believe if we sort the array, then set the data, runtime would still be nLog(n) compared to just looping and running repeated inserts. But I think it would avoid all the splice operations getting the initial data set in place.

**Comment by adamhooper** [comment]
Feel free to open another issue for that great suggestion :)
