### ISSUE TITLE
RedBlackTreeStrategy throws error when in should not?

### ISSUE THREAD

**Issue by grebenyuksv** [adamhooper/js-sorted-set#5]
Hey Adam, this piece of code does not work as expected, is it? Or am I missing something?

```
const set = new SortedSet({comparator: () => 0});
set.insert(0);
set.remove(0);
set.insert(1);
set.insert(2);
set.insert(3);
const min = set.beginIterator().value();
console.log(`${min} in set: ${set.contains(min)}`); // shows false
set.remove(min); // throws 'Value not in set'
```

**Comment by adamhooper** [comment]
Hi there,

That `comparator` is invalid. According to it, `0 == 1 == 2 == 3`. That means the set isn't sorted at all, so you get undefined behavior.

You need a [total order](https://en.wikipedia.org/wiki/Total_order) comparator. In this example, you probably want `const set = new SortedSet({ comparator: (a, b) => a - b })` -- which is the default, so you can just use `const set = new SortedSet()`.

I've tested your code with the default comparator, and it works as expected.

"Undefined behavior" could result in lots of things; in this case, it's a crash. Other implementations might return silently, or they might remove elements from the set that are not the element you requested to remove. However, only an incredibly slow algorithm would be able to detect this particular error in a comparator -- and no algorithm can detect errors in comparators in general.

So I feel comfortable closing this issue. Please use a valid comparator (or the default).

**Comment by grebenyuksv** [comment]
Ah, ok, thanks for clarifying this.
And thanks for your lib!
